### ISSUE TITLE
Implement Subtrach Function

### ISSUE THREAD

**Issue by sungohki** [chamdduk/four-arithmetic-operations#2]
### Description
Implement Subtract function for four arithmetic operations

### To-Do list
- [ ] Input first variable for subtract
- [ ] Input second variable to subtract first variable
- [ ] subract first variable by second variable
- [ ] print the result of subtract
